export type INCREASE_COUNTER = "CounterModule/INCREASE_COUNTER";
export const INCREASE_COUNTER: INCREASE_COUNTER = "CounterModule/INCREASE_COUNTER";

export type DECREASE_COUNTER = "CounterModule/DECREASE_COUNTER";
export const DECREASE_COUNTER: DECREASE_COUNTER = "CounterModule/DECREASE_COUNTER";
